stages:
  - test

.run-tests: &run-tests
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
  - pytest

test3.7:
  stage: test
  image: python:3.7-alpine
  script: *run-tests

test3.10:
  stage: test
  image: python:3.10-alpine
  script: *run-tests
